# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Quà Tặng 3A
    url: https://automation.nextsmarter.com
  - name: LP Quà Tặng 3A
    url: https://tuvan.quatang3a.com/qua-tang-doanh-nghiep
  - name: Nhãn Mác 3A
    url: https://nhanmac3a.vn/
  - name: LP Nhãn Mác 3A
    url: https://temkimloai.nhanmac3a.vn/
  - name: Tem Nhãn 3A Com
    url: https://temnhan3a.com/
  - name: Tem Nhãn 3A Vn
    url: https://temnhan3a.vn/
  - name: Dạ Quang 3A
    url: https://daquang3a.vn/
  - name: Biển Báo 3A
    url: https://bienbao3a.com/
  - name: Biển Báo 3A
    url: https://brandcharger.vn/
  - name: Make Your Sign
    url: https://makeyoursign.vn/
  - name: Vietbrandgift
    url: https://vietbrandgift.vn/
  - name: Going Green
    url: https://goinggreen.vn/
  - name: Korintech
    url: https://korintech.vn/
  - name: COI Event
    url: https://sukiencoi.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
