# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Quà Tặng 3A
    url: https://automation.nextsmarter.com
  - name: LP Quà Tặng 3A
    url: https://tuvan.quatang3a.com/qua-tang-doanh-nghiep
  - name: Nhãn Mác 3A
    url: https://nhanmac3a.vn/
  - name: LP Nhãn Mác 3A
    url: https://temkimloai.nhanmac3a.vn/
  - name: Tem Nhãn 3A Com
    url: https://temnhan3a.com/
  - name: Tem Nhãn 3A Vn
    url: https://temnhan3a.vn/
  - name: Dạ Quang 3A
    url: https://daquang3a.vn/
  - name: Biển Báo 3A
    url: https://bienbao3a.com/
  - name: Biển Báo 3A
    url: https://brandcharger.vn/
  - name: Make Your Sign
    url: https://makeyoursign.vn/
  - name: Vietbrandgift
    url: https://vietbrandgift.vn/
  - name: Going Green
    url: https://goinggreen.vn/
  - name: Korintech
    url: https://korintech.vn/
  - name: COI Event
    url: https://sukiencoi.com/
  - name: Pham Hai Nam
    url: https://phamhainam.com/
  - name: Mai Linh Mart
    url: https://mailinhmart.com/
  - name: Next Smarter
    url: https://nextsmarter.com/
  - name: Thi Cong Pro
    url: https://thicongpro.com/
  - name: Tinh Do Tong
    url: https://tinhdotong.com/
  - name: LEARNS
    url: https://learns.vn/
  - name: Be Tong Bao Nguyen
    url: https://betongbaonguyen.com/
committer:
  name: nextsmarter
  email: nextsmarter@example.com
status-website:
  baseUrl: /upptime
  name: NextSmarter Status
  introMessage: Trang theo dõi uptime các dịch vụ nội bộ
  theme: night
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/nextsmarter/upptime
i18n:
  live: Đang hoạt động
  down: Đang lỗi
  footermessage: Theo dõi bởi Upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
